<?php

namespace App\Controller\Admin;

use App\Libraries\Pagination\Paginator;
use App\Models\Members;
use Framework\Input;
use Framework\Response;

class ConfigController extends AdminController
{
    public $configData = array();
    private $filePath = '';
    private $provinces = array(
        296 => "An Giang",
        254 => "Bà Rịa - Vũng Tàu",
        209 => "Bắc Cạn",
        204 => "Bắc Giang",
        291 => "Bạc Liêu",
        222 => "Bắc Ninh",
        275 => "Bến Tre",
        256 => "Bình Định",
        274 => "Bình Dương",
        271 => "Bình Phước",
        252 => "Bình Thuận",
        290 => "Cà Mau",
        292 => "Cần Thơ",
        206 => "Cao Bằng",
        236 => "Đà Nẵng",
        262 => "Đắk Lắk",
        261 => "Đắk Nông",
        215 => "Điện Biên",
        251 => "Đồng Nai",
        277 => "Đồng Tháp",
        269 => "Gia Lai",
        226 => "Hà Nam",
        24 => "Hà Nội",
        239 => "Hà Tĩnh",
        220 => "Hải Dương",
        225 => "Hải Phòng",
        293 => "Hậu Giang",
        28 => "Hồ Chí Minh",
        221 => "Hưng Yên",
        258 => "Khánh Hoà",
        297 => "Kiên Giang",
        260 => "Kon Tum",
        213 => "Lai Châu",
        263 => "Lâm Đồng",
        205 => "Lạng Sơn",
        214 => "Lào Cai",
        272 => "Long An",
        228 => "Nam Định",
        238 => "Nghệ An",
        229 => "Ninh Bình",
        259 => "Ninh Thuận",
        257 => "Phú Yên",
        232 => "Quảng Bình",
        235 => "Quảng Nam",
        255 => "Quảng Ngãi",
        203 => "Quảng Ninh",
        233 => "Quảng Trị",
        299 => "Sóc Trăng",
        212 => "Sơn La",
        276 => "Tây Ninh",
        227 => "Thái Bình",
        208 => "Thái Nguyên",
        237 => "Thanh Hóa",
        234 => "Thừa Thiên Huế",
        273 => "Tiền Giang",
        294 => "Trà Vinh",
        207 => "Tuyên Quang",
        270 => "Vĩnh Long",
        216 => "Yên Bái",
    );
    public function __construct()
    {
        parent::__construct(); // TODO: Change the autogenerated stub
        $this->filePath = __APP__ . '/config/prices.php';
        $this->setTitle('Config System');
        $this->configData = include $this->filePath;
    }

    public function edit()
    {
        return $this->render('admin.config.edit')->with(array('data' => $this->configData, 'provinces' => $this->provinces));
    }

    function save()
    {
        try {
            $data = Input::getAllData();
            $this->configData = $data['parameters']['data'];
            file_put_contents($this->filePath, '<?php return ' . var_export($this->configData, true) . ';');
            return Response::redirect(url('admin/config'));
        } catch (\Exception $e) {

        }
    }
}
