<?php

namespace App\Controller\Admin;

use App\Libraries\Pagination\Paginator;
use App\Models\Members;
use Framework\Input;
use Framework\Response;

class ConfigController extends AdminController
{
    public $configData = array();
    private $filePath ='';
    public function __construct()
    {
        parent::__construct(); // TODO: Change the autogenerated stub
        $this->filePath = __APP__ . '/config/prices.php';
        $this->setTitle('Prices Config');
        $this->configData = include $this->filePath;
    }

    public function edit()
    {
        return $this->render('admin.config.edit')->with(array('data' => $this->configData));
    }

    function save() {
        try {
            $data = Input::getAllData();
            $this->configData = $data['parameters']['data'];
            file_put_contents($this->filePath, '<?php return ' . var_export($this->configData, true) . ';');
            return Response::redirect(url('admin/config'));
        } catch (\Exception $e) {

        }
    }
}
