<?php

namespace App\Controller\Admin;

use Framework\Config;
use App\Libraries\PhoneCharge;

class TestController extends AdminController
{
    public function __construct()
    {
        parent::__construct(); // TODO: Change the autogenerated stub
        $this->setTitle('Test');
        $this->config = config('prices');

    }

    public function index()
    {
        $phones = [
            '0976553987' => 120,
            '02873081616' => 21,
            '002873081616' => 211,
            '006173081616' => 211,
            '02473011616' => 211,
            '624709' => 2112,
        ];
        foreach ($phones as $phone => $sec) {
            debug("Phone: {$phone} --- Thoi gian {$sec} (s)");
            $phone_charge = PhoneCharge::getInstance($this->config)->phone_charged($phone, $sec);
            debug("Cost: {$phone_charge} (vnd)");
            debug("==============================================================================================");
        }
    }
}
